### ISSUE TITLE
Blokada turns off when WiFi is off and doesn't turn back on by itself after WiFi is back on (online only is off)

### ISSUE THREAD

**Issue by w4tadrag** [blokadaorg/blokada#126]
Hi, 

### Steps to reproduce
1. Be on WiFi and have Blokada on
2. Turn off WiFi from notification menu

### Expected behaviour
Doing this should not turn off Blokada. Also just keep in mind I have **unchecked** Online only 

### Actual behaviour
 It turns off Blokada and removes the VPN icon from the status bar. Although it doesn't remove the notification bar. It doesn't turn back on when I turn WiFi back on. Even if I launch the app, it won't turn on, it says "Blokada is inactive". So I have to press the power icon in the app to turn it back on.  

### Configuration
1. Blokada version
Blokada 3.0.0-preview2

2. Device model
OnePlus One 
A0001

3. Android version / ROM
Android OS: 5.1.1
OxygenOS 2.1.4

### Questions
1. How long have you been using Blokada? 
3-4months

2. How long time ago has the problem started to happen? 
after downloading the preview2 (didn't try the 1st preview). 

3.  How often does this problem happen to you?
I have tried this test many times. Same thing happens all the time.

I hope you can resolve this before you release the official build
Btw 1 other question, if I block all notification from Blokada and I have **Keep Alive on**, would Android still kill the app?

Thanks for your help :)

**Comment by kar** [comment]
Can't reproduce so far. Anyone?

**Comment by kar** [comment]
>  Although it doesn't remove the notification bar.
You mean you have the Keep Alive on?

> if I block all notification from Blokada and I have Keep Alive on, would Android still kill the app?
Blocking all notifications should not affect it.

**Comment by w4tadrag** [comment]
Hi, I made a video that shows the issue. Link below:

https://drive.google.com/file/d/1o_FtLiERJfPbgkHQsQBXqa4o7ZQUBHNt/view


Also, just an update to the auto turn on, it looks like the app **does turn on** by itself after WiFi is activated most of the time now.

But I guess the issue here is I didn't choose online only, but it's doing the actions for that option.

Hope this helps and thanks for answering the question :)

**Comment by kar** [comment]
Great bug report, thank you. So we can see that Blokada is trying to turn on (those "vpn key flashing" moments), but fails almost instantly. Blokada uses exponential cooldown if it can't connect quickly, meaning it retries after longer and longer waiting, that's why if you keep your wifi off for some time, the reconnect will be "slow".

Something on your device makes the VPN fail instantly when turning off wifi (and there is no other connectivity). You may try the "VPN always on" android setting (I think it was available in Android 5?).

**Comment by kar** [comment]
If you turn on "Online Only" the behavior should be a bit different. It should disconnect, and not retry at all (no "vpn key flashing") until you turn on the wifi back, and then it should activate quickly.

Since it doesn't seem a widespread issue, I'll schedule it to 3.1. If anyone experiencing this also, please comment.

**Comment by kar** [comment]
I was able to reproduce on another device.
