### ISSUE TITLE
Blokada regularly blocks all traffic after connection switch on Samsung S9+

### ISSUE THREAD

**Issue by arjan-s** [blokadaorg/blokada#139]
### Steps to reproduce
1. Ensure Blokada is running and blocking ads, but not hindering other traffic
2. Disable or enable wifi or mobile data
3. Ensure Blokada is connected again (usually takes a few tries)
4. Verify all data is blocked by starting any app that requires internet connection

### Expected behaviour

Blokada should never block all traffic on the device.

### Actual behaviour

No app can access the internet. At least Chrome gives an error code: DNS_PROBE_FINISHED_BAD_CONFIG.

After a reboot of the phone, Blokada always works correctly. Sometimes it also starts working again after some more connection switches.
Using another VPN in between Blokada sessions also sometimes messes it up.

Somewhat funny: the "Online only" switch enabled causes Blokada to get into a kind of restarting loop, where it detects internet, starts Blokada, detects internet gone, disables Blokada, detects internet, starts Blokada, etc...

### Configuration
1. Blokada version
3.0.0

2. Device model
Samsung Galaxy S9+

3. Android version / ROM
Stock ROM, Android 8.0.0

### Questions
1. How long have you been using Blokada? 
Almost a week.

2. How long time ago has the problem started to happen? 
Right from the beginning.

3.  How often does this problem happen to you?
Most of the times I switch network connections (wifi / mobile data). Not always though.

**Comment by kar** [comment]
Could you retry this with 3.1.1?

**Comment by arjan-s** [comment]
F-Droid still shows 3.0.0 as the newest version... But I installed Blokada 3.1.1 from blokada.org, and it seems to work correctly now. Great!
Although I must admit that I switched over to SABS since I'm using a Samsung device. :)

**Comment by tenpaiyomi** [comment]
@kar

Replying here since I am experiencing this exact same issue on a Note 9 with version 3.6

### Steps to reproduce
Same as OP

### Expected behaviour
Internet to pick up and continue to work as expected after handoff from one network type to another.

### Actual behaviour
Same as OP in that internet just seems to be connected (either wifi or 4G) however nothing that utilizes internet works, In addition to that, if I completely turn of Blokada and disconnect from the VPN, internet will start working again.  As well, if I turn off Blokada, it does not seem to disconnect from the VPN and I get stuck in an odd "connected to VPN but Blokada is not active" state.  I noted that in this "not working" state, if I whitelist an app from Blokada, internet will work for it.

### Configuration
1. **Blokada version:** 3.6

2. **Device model:** Samsung Note 9

3. **Android version / ROM:** Stock (Samsung) 8.1.0

### Questions
1. **How long have you been using Blokada?** On this device, for about a week.  Prior to this I used Blockada on a Pixel 2 XL for about a year without experiencing this issue.

2. **How long time ago has the problem started to happen?** Since day 1

3.  **How often does this problem happen to you?** Daily, basically whenever a network switch occurs.

**Comment by kar** [comment]
1. Update to today's version if you haven't yet
2. Turn off watchdog
3. Turn off any battery optimizations / auto launch control and such things in your system preferences (for Blokada)

**Comment by tenpaiyomi** [comment]
@kar 

Issue occurred again this afternoon.  Steps in which everything occurred:

1. Was on home wifi
2. Left home, phone switched to 4G, full signal
3. Arrived at destination, opened up browser, noted that no pages were loading
4. Confirmed that phone still showed Blokada as active and VPN connected
5. From the Blokada UI, disabled Blokada, tested internet.  Still no connectivity.
6. Phone still showed as connected to VPN even though Blokada was disabled.
7. Manually disconnected from VPN, tested internet.  Connectivity established, got a plethora of notifications as everything started communicating with internet again.

**Comment by ZirconZer0** [comment]
I am also having the same problem except I am using S9+ Snapdragon version. The issue can temporarily be solved by rebooting the device. However, it will come back after a few days. I was using version 3.5 of Blokada and had no problem at all. Upgraded to 3.6 and the problem appeared. I tried downgrading back to 3.5 but the issue persists. I think there is a conflict between the app and Samsung's Android os. Hopefully the developer can look into this. Thanks.

**Comment by lijuenc** [comment]
Why is this issue closed? Only way to restore functionality right now is to restart the device as mentioned above and at this point I'm having to restart every 1-2 days because of Blokada.

**Comment by rpeter85** [comment]
Issue is tracked in #284
