### ISSUE TITLE
I want the update apks to be saved in standard Download folder of Android

### ISSUE THREAD

**Issue by ilkercnsy** [blokadaorg/blokada#163]
This is where they are being saved: https://i.hizliresim.com/JQJlk5.jpg

If you change this, we could easily access the file through File Managers, no need to go to download manager at all.

**Comment by kar** [comment]
I'll not change the download location for now, the nice thing about the current location is that its wiped when the app is uninstalled so no mess is left. I have reworked the update process to give more feedback (download percentage progress and other info), and it should be more convenient now. Once 4.4 is out (and when updating to 4.5 since only then you will see it... :D) please try it out and if it won't be enough feel free to comment here.
