### ISSUE TITLE
I want an option for domain black/whitelist logging

### ISSUE THREAD

**Issue by aussie-damo** [blokadaorg/blokada#178]
I would love the option to see the logs (realtime or snapshot) of the whitelist/blacklist to help troubleshoot or add/remove sites to the lists. Similar to the notification but an actual list that can be turned on and off (off by default) and maybe a file size max (0.1-100MB as it's only text) to go with it (to prevent 2GB+ log files).   

If we could have the lists with a block/allow button next to the domains to automatically add them to white/blacklists it would be great but just the logs to help troubleshoot would be great.

**Comment by kar** [comment]
#121

**Comment by hoshsadiq** [comment]
This would be great. Currently addons.mozilla.org is blocked when I Blokada is enabled, and I struggle to find out which list is blocking it.

What would also be cool (though I can imagine it being a bit too much to ask), is if there's an option to export it when on a network. Specifically, I run pi-hole at home, and all data gets extracted and pushed into Prometheus, which then has Grafana in front for nice graphs. It would be great to be able to easily push Blokada's logs into Prometheus

**Comment by kar** [comment]
Nice idea @hoshsadiq. I'll keep this in mind when implementing the log feature. Can you link me to some documentation on what kind of log format prometheus expects?

**Comment by hoshsadiq** [comment]
Sorry, I received your message, but haven't had the chance to give you an answer. Will do so soon hopefully!

**Comment by jawz101** [comment]
Something along the lines of NetGuard's logging features.  When I can see what sorts of DNS traffic are happening I can build better blacklists.   Most of the precanned hostfile blacklists are developed around desktop browser traffic and don't have much in the way of mobile ad network domains.  I've been using Adaway's logging functions and NetGuard's logging functions to find new domains.

Actually, I've amassed about 1700, half of which aren't covered by other lists and when I use my host file list Blokada lights up.  I've also scraped from a few other sources as well.

https://github.com/jawz101/MobileAdTrackers

BTW, Adaway's list hasn't been officially updated since 2016.  Its last update was by me but it was reverted due to an accidental block of goo.gl.  I just don't care to try to get it readded but their list is basically worthless, IMO.

**Comment by colbycdev** [comment]
Ooh, sorry @rpeter85. Didn't see this. Guess I should have looked farther back, huh.
In that case, this issue has my full support.  

_Sent from my TETRA using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by rpeter85** [comment]
I think this feature is implemented in Blokada v4.

**Comment by aussie-damo** [comment]
I started this back when blockada was version 3.2.

**Comment by rpeter85** [comment]
I know :) I'm about to close this case, but wanted to clarify if the feature you asked for is shipped.
