### ISSUE TITLE
Blokada can get stuck in activating after reboot

### ISSUE THREAD

**Issue by kar** [blokadaorg/blokada#19]
I had blokada on and restarted my phone due to an issue. When I did, the activation of the VPN was stuck on activating.. Tried to force stop and retried its still in activating.

**Comment by kar** [comment]
Android 6.0.1

**Comment by Mbharath003** [comment]
Phone - Lenovo Vibe P1.. Model - P1a42

When it is active it works fine. Will report what i come across. Cheers.

**Comment by Mbharath003** [comment]
Got it working after a quick clear data. Seems fine now.

**Comment by Sylriel** [comment]
I don't know if I am encountering this problem. Every time I reboot I see no action from the app. When I open the app, it is stuck at activating. Then it asks me if I want to turn it on in a pop up that appears as few seconds later. I have it set to turn on at boot.

I hate to compare but when I was using Adguard it doesn't automatically launch on boot either but at least it gives me an pop up on boot that asks me if I want to turn it on.

**Comment by kar** [comment]
Anyone could verify it's fine in 1.1.1?

**Comment by Sylriel** [comment]
I have only had 1.1.1 installed on my phone and that's what I am referring to when I made my post.

I have Keep Alive and Start on Boot turned on.  When I turn on my phone from complete power off or if I reboot Blokada does not start. However I will see a status saying 0 Ads blocked when I check status.  
![screenshot_2017-04-10-16-44-21](https://cloud.githubusercontent.com/assets/26077374/24882712/145ab6e6-1e10-11e7-8bbf-3d52cd39eea8.png)

I then either click on the status to launch Blokada or launch Blokada from shortcut/drawer.  When Blokada starts the Blokada logo will be in orange instead of red with the status Blokada is paused.  
![screenshot_2017-04-10-16-44-57](https://cloud.githubusercontent.com/assets/26077374/24882763/3b3fec90-1e10-11e7-8617-b35db8d4b6e3.png)

Then a few seconds later a pop up will appear telling me Blokada is attempting to start VPN.  Blokada then goes active when I check the check box saying I trust it and click OK.  
![screenshot_2017-04-10-16-45-06](https://cloud.githubusercontent.com/assets/26077374/24882779/44a40604-1e10-11e7-9383-2ec3a8022795.png)

On some rare occasions I will not receive the pop up. In those occasions I have to go to the task list and turn off Blokada and relaunch it.

I attached some images that show what I am seeing (I hope they show).  Please see if you can fix. Thanks.

**Comment by kar** [comment]
Great input, thanks!

**Comment by Zero3K** [comment]
I don't think this has been fixed yet in the new version. I still had to manually stop its activation and re-enable it for it to work.

**Comment by kar** [comment]
There're some more fixes related to this in the pipeline, just not released yet. But let's keep an eye on it in the next version.
