### ISSUE TITLE
[Request] Add this small hosts list to block most Android trackers

### ISSUE THREAD

**Issue by beerisgood** [blokadaorg/blokada#261]
This small hosts [list](https://gist.githubusercontent.com/mattradford/50a6f8331a920afe9c8471e12414831f/raw/2d45c7a798b49ca89a5c1bf1005e5abce67f6ac5/exodus-list) block most of known trackers founded in [Exodus](https://reports.exodus-privacy.eu.org/trackers/)

Should be enabled in Blokada by default or included in other default lists.

**Comment by kar** [comment]
Nice. Any kind of homepage for this list?

**Comment by beerisgood** [comment]
Homepage/ source is in #2 line in that list

**Comment by jawz101** [comment]
Might I recommend my list?
https://github.com/jawz101/MobileAdTrackers

**Comment by beerisgood** [comment]
Also this lists is nice too: https://media.kuketz.de/lists/mobile_list.txt
(From a german IT security & privacy blog): https://www.kuketz-blog.de/tracking-und-ads-filterliste-vom-kuketz-blog/

@jawz101 you should include these domains too. Also looks you already include the domains from my first post. Nice!

**Comment by rpeter85** [comment]
Before every recommended lists are included, can you please check if the hosts in those lists aren't included in another list (for example Energized asic or a bigger one)? Blokada filters duplicates and it's useless to enable a list that hosts' are already 1:1 included in one

**Comment by jawz101** [comment]
I believe energized might merge mine into theirs.

**Comment by rpeter85** [comment]
@beerisgood could you check if the list you mentioned isn't present in another list, like in Goodbye Ads or Energized?

**Comment by beerisgood** [comment]
> 
> 
> @beerisgood could you check if the list you mentioned isn't present in another list, like in Goodbye Ads or Energized?

My [first](https://gist.githubusercontent.com/mattradford/50a6f8331a920afe9c8471e12414831f/raw/2d45c7a798b49ca89a5c1bf1005e5abce67f6ac5/exodus-list) posted link is included in [GoodbyeAds](https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Hosts/GoodbyeAds.txt)

Same for second list from [Kuketz](https://media.kuketz.de/lists/mobile_list.txt), but without these domains:
* app-measurement.com
* yandex.ru

**Comment by MicroBeast** [comment]
Per Blokada 3.6.101900, the default hosts list was Energized Blu.
This list seem too overkill. I found informaction.com was blocked, that domain used by NoScript forum.

I don't know what else this list broke, I rarely visit random site except those known famous these days. So, consider my post as just an info if some people come ranting here. Sure advance users know what to do if something broke.

Oh, and don't bother to try Energized Ultimate. From uBlock0 logger, it blocked so many networks I'm too scared to imagine.

**Comment by jawz101** [comment]
Personally, I just like Steven Blacks and mine.  An equivalent list might be the Energized Spark list, but reading what lists are in the bigger packages, and trying them on my pfSense box, they get very retarded very quickly as you go up to any of the larger Energized lists.

**Comment by beerisgood** [comment]
StevenBlack doesn't include the domains from list I posted

**Comment by colbycdev** [comment]
How about this extreme extension from Energized? On almost every list, >4k hosts aren't included.  

_Sent from my TETRA using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by colbycdev** [comment]
Energized doesn't have many false positives (in my experience) and you can whitelist sites if needed

**Comment by rpeter85** [comment]
@jawz101 MAT will be added to the default lists soon, thank you for the recommendation.

kuketz.de's list is unavailable, couldn't check that. Seems they closed their doors.

**Comment by eladkarako** [comment]
@beerisgood that's a great list but in its current state it is only useful as a 
browser's adblock-rules (https://github.com/gorhill/uBlock/releases) since it misses 
most of the actual subdomains that are used in ads-downloading, report sending, etc...

See this micro-list I've composed to use in my D-Link router, 
(it only had 40-places in its admin web-interface...)

<pre>
pagead2.googlesyndication.com
googleads.g.doubleclick.net
pubads.g.doubleclick.net
adserver.adtechus.com
widgets.outbrain.com
adserver.adtech.de
ad.doubleclick.net
adclick.g.doubleclick.net
odb.outbrain.com
ad.atdmt.com
adsserving.net
static.doubleclick.net
www.googletagservices.com
adnxs.com
ads.trafficjunky.net
advertising.com
doubleclick.net
stats.g.doubleclick.net
cm.g.doubleclick.net
securepubads.g.doubleclick.net
securepubads.g.doubleclick.com
pagead2.googlesyndication.net
media.admob.com
admob.com
pagead.l.doubleclick.net
server.exposebox.com
pagead2.googleadservices.com
googleadservices.com
www.googletagmanager.com
googletagmanager.com
api.crashlytics.com
bid.g.doubleclick.net
crashlytics.com
cm.crashlytics.com
e.crashlytics.com
reports.crashlytics.com
settings.crashlytics.com
support.crashlytics.com
tpc.googlesyndication.com
c.amazon-adsystem.com
</pre>

as you can see `crashlytics.com` is used along with `reports.crashlytics.com`, 
blocking `doubleclick.net` is ok I guess, but note that most of the native google gms ads are downloaded from `securepubads.g.doubleclick.net` now.

I'm using tools such as https://github.com/eladkarako/Domain-subdomains-With-VirusTotal-API-and-NodeJS (along with my virustotal API key) to grab more sub-domains for each new domain I find.

Here is what I got after running that tool for each of your domains in the list, 
along with adding the common `www` subdomain for each one, 
and it is also possible to add the `wss` and `ws` subdomains to block potential websocket connections.

Naturally those kind of lists tend to get really big, and not every domain uses the `www` or `wss` subdomain... 
... this is why when I've tries to auto-generate a HOSTS list of my own (https://hosts.eladkarako.com), but it got to about 40MB including all those sub-domains... :))

Most of the android apps can't handle those sizes, so its mostly used for a HOSTS replacement in windows and rooted linux/android devices.
