### ISSUE TITLE
I want to redesign UI and UX

### ISSUE THREAD

**Issue by kar** [blokadaorg/blokada#278]
We now know enough about the problems with the current UI. A redesign should address the following (ordered by priority):

- [x] Support Smart TV & firestick devices better. Remote navigation, also through dialogs, and general goodness for this kind of devices
- [x] Support blocking log feature, possibly with some graphs and stats in the future
- [x] Improve virality with sharing the block counter on social media and other ideas
- [x] Support tablets better
- [x] Support RTL and dynamic language change
- [x] Support all the new planned features mentioned in other issues (ie. make UI navigationally make sense to accommodate planned features)
- [x] Address UI bugs mentioned in other issues

Technicalities to address:
- [ ] Get rid of the following concepts: Dash, Actor
- [ ] Use a modern library for dynamic lists (LastAdapter?)
- [ ] Eliminate code duplication in UI code
- [ ] Consider using modern Android components (LiveData, ViewModel, ...)
- [ ] Use MVVM in one form or another
- [ ] Enforce strict policy of dumb views
- [ ] With the new code, ensure the new modular approach is followed

**Comment by colbycdev** [comment]
Great idea. I'd also recommend, but I suppose if demand isn't very high, it won't get implemented, recommended lists based on device resources rather than a default. For instance, devices with 1gb ram or less go with Blu Spark, 2gb or less Blu go, 4gb or less Blu, 4gb and up Basic (energized lists) 

_Sent from my TETRA using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by kowith337** [comment]
Can you please disable any popups of your apps that show often?

I'm try to config your apps, view how many hosts file I've loaded, etc. But I get a popup from your apps on the way at everytime I launch your app, that's so very annoying.
