### ISSUE TITLE
Blokada does not seem to disconnect consistently when watchdog mode is enabled and internet connectivity is shut off

### ISSUE THREAD

**Issue by matteocoder** [blokadaorg/blokada#297]
### Steps to reproduce
1. Start Blokada with watchdog mode on while being connected to the internet (either WiFi or data)
2. Shut off internet connectivity

### Expected behaviour
Blokada should pause and the phone should be disconnected from the VPN (the key icon on the status bar and the "network may be monitored" notice should disappear every time.

### Actual behaviour
While Blokada always says that it is paused as it should, the phone does not always disconnect from the VPN and shows that Blokada is still active. This happens whether the "always-on VPN" setting is active or not.

### Configuration
1. Blokada version
3.6.101900

2. Device model
Motorola Moto G4

3. Android version / ROM
Stock ROM Android 7.0

### Questions
1. How long have you been using Blokada? 
Since version 3.4

2. How long time ago has the problem started to happen? 
After updating to version 3.6

3.  How often does this problem happen to you?
It happens inconsistently, but often.

Thanks for developing this awesome app!

**Comment by colbycdev** [comment]
I know sometimes when I manually disconnect, Blokada stays connected since version 3.5, on an Alcatel Tetra running Android 8.1.

On Dec 2, 2018 7:14 AM, matteocoder <notifications@github.com> wrote:
Steps to reproduce

  1.  Start Blokada with watchdog mode on while being connected to the internet (either WiFi or data)
  2.  Shut off internet connectivity

Expected behaviour

Blokada should pause and the phone should be disconnected from the VPN (the key icon on the status bar and the "network may be monitored" notice should disappear every time.

Actual behaviour

While Blokada always says that it is paused as it should, the phone does not always disconnect from the VPN and shows that Blokada is still active. This happens whether the "always-on VPN" setting is active or not.

Configuration

  1.  Blokada version
3.6.101900

  2.  Device model
Motorola Moto G4

  3.  Android version / ROM
Stock ROM Android 7.0

Questions

  1.  How long have you been using Blokada?
Since version 3.4

  2.  How long time ago has the problem started to happen?
After updating to version 3.6

  3.  How often does this problem happen to you?
It happens inconsistently, but often.

Thanks for developing this awesome app!

**Comment by matteocoder** [comment]
I've noticed another interesting behavior:

1) have Blokada on with both "watchdog mode" and "start on boot" settings enabled;
2) turn on airplane mode;
3) reboot the phone.

In this scenario Blokada will start normally after the reboot, even though the phone is still in airplane mode (and without Wifi connectivity), seemingly ignoring "watchdog mode".

**Comment by animeking9901** [comment]
Alcatel in general seems to be fiddly on this matter as I've seen this type of behavior before

**Comment by rpeter85** [comment]
Hi,
Can you check if you face the same behaviour with Blokada 4.3.5?

**Comment by matteocoder** [comment]
Hello @rpeter85, thanks for taking interest in this issue. I have to tell you that now I've upgraded my phone to Android 8.1. Fortunately it seems that blokada correctly detects that there is no internet connectivity and says that it is paused. The VPN notification seems to disappear only if, after turning off internet connectivity, I open a browser tab like a new chrome tab or a chrome custom tab inside an app. This makes me wonder if it is actually Android's fault and how it interacts with blokada.

**Comment by kar** [comment]
Yes thats ok.
