### ISSUE TITLE
Feature Request: opt-in for sending logs

### ISSUE THREAD

**Issue by kreisklasse** [blokadaorg/blokada#323]
Built feature to let people opt-in sending the crash log file, not doing it automatically.
Also show log-file prior sending it.

Workflow:
1. blokada detected crash after restart
2. user is asked to send crash log, if he agrees
3. user is shown the log file and a request to send it to blokada.org

reported as bug, no closed #322

**Comment by davb5** [comment]
Agreed, should definitely be opt-in (i.e. require a user actively choose to share logs rather than assume they agree).

The main reason I'm using Blokada over commercial alternatives is that I trust it more than proprietary software, from a privacy perspective. And one of the main reasons I'm using a host-based ad blocker (vs a browser based filter) is to stop analytics and crash reporting requests in other apps.

Crash reporting may seen innocuous but many crash analytics libraries make a startup call (even when no crash has occurred) - my banks app certainly does this. It would allow interested partied to build a fairly comprehensive view of how I use my device (I check my bank several times per day, maybe I have money worries. I open my health records app regularly - perhaps I'm ill and thus an insurance risk). I would rather just block *all* analytics by default and I absolutely need to trust my filter software.

**Comment by rpeter85** [comment]
This feature is shipped with version 3.7. Thank you for asking for it.

**Comment by Dustie** [comment]
This seem to have either broken or not been implemented correctly. I can see in Pi-hole that the domain is getting blocked even though Reports is set to No in the app.
