### ISSUE TITLE
Advantages over DNS66

### ISSUE THREAD

**Issue by noxarivis** [blokadaorg/blokada#34]
What are the advantages over DNS66?
https://github.com/julian-klode/dns66

**Comment by SMed79** [comment]
@kar If this project [is derived](https://github.com/julian-klode/dns66/issues/187#issuecomment-326161489) from [DNS66](https://github.com/julian-klode/dns66), I think you have a moral and ethical obligation to mention this.

**Comment by noxarivis** [comment]
@SMed79
they seem to created it by themselves. the codebase is very different

**Comment by SMed79** [comment]
Ok, Thanks.

**Comment by kar** [comment]
Those are two parallel projects developed roughly at the same time (Blokada got open sourced later though). 

Blokada has two blocking mechanisms, the "Standard blocking" and the "Optimised blocking". The "Standard blocking" is the older one and works on Android 4, although has worse battery use characteristics than the "Optimised blocking", which was based on how DNS66 does it. It's lighter on battery, but more limited, hence some coming features may not be supported by it (plus, it breaks things like Google Play downloads and hence requires some apps to be whitelisted). I introduced it since some people are fine with just simple ad blocking without bells and whistles. I just learnt that by doing so, I broke the GPL license, so I'm going to replace it with a new solution in the coming days.

The rest of the features is similar but developed independently, so you may find that one app works better for you than the other. For example, many people compliment the UI of Blokada. Also, Blokada has some configuration switches you can play with, that may make it work better on your device. Just try both apps and see what you like more.

PS: I always appreciate feedback on what you like or don't like in Blokada. :)
