### ISSUE TITLE
I want to set blokada as a device admin

### ISSUE THREAD

**Issue by hoshi411** [blokadaorg/blokada#357]
I have blokada setup on my child's phone and want her to have access to force quit ability but at the same time not be allowed to force quit blokada.  This can be done by seting it as a device admin as many parental apps have the ability to do.  The ability to force quit them is then greyed out.

**Comment by Thomas499** [comment]
1. In my experience, the college kids who had over-controlling parents growing up were the most "active" and not in the way most parents want. Take that advice as you like. Over controlling will backfire but that's your choice to make. 

2. I have no no idea what you mean by want her to have access to force quick but at same time not be allowed to force quit blokada. This sounds contradictive. 

3. What do you think will happen when kid who knows force closing blokada will allow them to access whatever they want to access, realized they can not force close blokada. - What I would do is back up the app, delete the installed app, access whatever I wanted, then re-install the back up. - Do you want ability to prevent child from deleting app too or just preventing the kid from force closing it?

4. TO accomplish what I think you want, best bet is to a raspberry pi and install pi hole. Set your router to use the pi holes address as it's DNS. Then, every device on your network will be blocked and the only way the kid can bypass it is to either access the router admin credentials assuming they know what DNS is and that is what is causing their problem (unlikely), or accessing the internet through method other than through the homes wifi modem. 

Might be a good idea to explain what you want is instead of a private network, you really want a local DNS that can block content on a network side that the kid doesn't have access to change. 

Best approach is probably to go into their phone settings and change the DNS. Here are instructions how to do it. https://www.lifewire.com/how-to-change-dns-on-android-4588645 I doubt the kid will be able to figure out how to change it because they won't be to figure out what to even google. Because blokada doesn't allow you to use your firestick to create a network DNS that can block specifically what you want, you will probably have to use adguard. More details here if you are interested https://adguard.com/en/adguard-dns/overview.html#instruction use 176.103.130.130 and 
176.103.130.131 for the DNS for normal blocking. Simply change the last number to 132 and 134 to block porn. - Personally, I really don't recommend that though. You can also change the DNS on the router directly but that will not block from access while using 3g. 

Out of curiosity, would you donate $5 to the creator of blokada if he went out of his way to create a parent control version of blokada that allowed you to prevent your child from force closing it?

**Comment by hoshi411** [comment]
Hmm.  My subjective reasonings aside.  My request is the ability to setup blokada as a device admin.  The story about the girl is a hypothetical.  I could give countless hypothetical situations where the ability to setup blokada as a device admin would greatly improved the power and functionality of the app.  

Not being able to set it as a device admin cripples so much of its potential usefulness.

**Comment by Thomas499** [comment]
I must admit, I seriously doubt schools would use blokada over their DNS methods. Blokada only works on android. It won't work on windows computers or apple i pads. DNS works on all devices and is easily manageable from a single location. 

I believe if blokada could serve as a DNS that would be helpful. Other DNS's that I am aware of do not allow users to block custom sites. Maybe some allow it for a monthly fee. 

> If you can get around that by simply force quitting the app, there is no point in having the function to blacklist a site in the first place.

Just to clarify, do you want the app to not be delete-able without admin privileges as well? Can you name an app that can not be deleted without device admin (parent) privileges? 

> If you have the self control to not enter the site into a browser, why take the trouble to enter it into a block list of an app that can simply be force quit?

Everyone I know uses blokada to block ads, malware, and sometimes trackers. The things they would not intentionally enter into a browser anyway.

**Comment by hoshi411** [comment]
Thank you Thomas.
The piehole idea is a good one and one that I want to get around to at one point. 

Preventing blokada from being deleted is easily done with this app 

https://play.google.com/store/apps/details?id=com.sp.protector.free

That is not the problem.

I want to prevent blokada from being "force quit" 

Giving it admin privileges is how apps like this

https://play.google.com/store/apps/details?id=com.sp.protector.free

Prevent themselves from being forced down.

I already have blokada setup to not be deleted.

The problem is it can easily be force quit.

This could be easily prevented with the option to set it as device admin.  

I don't want blokada to turn into a parental app making it bloated with a whole bunch of options which other apps do fine.  I just want what I requested;

The ability to add blokada as a device admin.

That would allow people to use it in a lot of hypothetical scenarios.

**Comment by Thomas499** [comment]
> The piehole idea is a good one and one that I want to get around to at one point.

So if blokada could be installed on a firestick, and work the same way as pihole (as a DNS which couldn't be forced stopped on the kids phone as the program is running on a separate device which the kid doesn't have access to), would you buy a firestick and use blokada as a DNS rather than purchase a raspberry pi and spend an hour setting up the raspberry pi and installing pi hole on it?

**Comment by alexa-v2** [comment]
I'd like to see it as device admin to prevent _me_ from accidentally removing it or killing it myself :-)

**Comment by kar** [comment]
Good point, but device admin is deprecated and going away with Android Q....

**Comment by alexa-v2** [comment]
@kar could you link the relevant docs or info for educational purposes?

**Comment by hoshi411** [comment]
"... device admin is deprecated and going away with Android Q..."

Yikes.  But they will need to replace it with something and the developers would be up on that of course.

**Comment by kar** [comment]
They are moving to something called Android Enterprise. Similar APIs will be available, but you'll need to enrol your device to a specific organisation, which will require factory reset. We could do some cool things with those APIs, but asking for factory reset sounds like a lot :P

**Comment by kar** [comment]
https://developers.google.com/android/work/device-admin-deprecation
