### ISSUE TITLE
Blokada takes long time to start up 

### ISSUE THREAD

**Issue by mogarithm** [blokadaorg/blokada#403]
### Steps to reproduce
1. Ensure Blokada is not running. Use wifi. 
2. Launch Blokada.
3. Status will cycle between "Blokada is inactive" and "Loading please wait" over and over for sometimes two minutes. 
4. Eventually status will become "Blokada is active".

Settings:

Blocklist: Energized Blu (recommended)
Whitelist: Google Play Store, Download Manager, Drive, Gmail, Photos, Phone
DNS: Default DNS servers
Notifications: off
217237 hosts (959000 can fit in memory)
Download lists: once a month
Download on wifi only: on
Start on boot: on
Keep alive: on
Watchdog: off
Aggressive wakeup: off
DNS fallback: off
Reports: off

Android settingsL
Blokada: optimising battery use
Blokada: allow auto-start

### Expected behaviour
Blokada should go to "active" status within 10 seconds. 

### Actual behaviour
Blokada goes to "active" status usually after 70 seconds, although the amount of time can vary.

### Configuration
1. Blokada version
3.7 (022000) Official

2. Device model
Lenovo P2

3. Android version / ROM
7.0 

### Questions
1. How long have you been using Blokada? 
1 year

2. How long time ago has the problem started to happen? 
6 months

3.  How often does this problem happen to you?
Almost every time I start up Blokada. Very occasionally it instantly becomes active.

**Comment by rpeter85** [comment]
What does "take long" mean exactly?

**Comment by mogarithm** [comment]
> What does "take long" mean exactly?

A stated:
Expected behaviour
Blokada should go to "active" status within 10 seconds.

Actual behaviour
Blokada goes to "active" status usually after 70 seconds, although the amount of time can vary.

Device specs:
Chipset | Qualcomm MSM8953 Snapdragon 625 (14 nm)
CPU | Octa-core 2.0 GHz Cortex-A53

Wifi speed: 11.6Mbps download

**Comment by Thomas499** [comment]
**Recommendations for programmers:**

1. if blokada isn't active, the list shouldn't be downloaded, and the update process shouldn't happen. There is no reason for this process to happen when blokada is first installed, then again when user turns blokada on. 

2. download/update process shouldn't happen each time user accesses advanced settings, or changes an advanced setting such as download once a month instead of once a day. Currently, once a day is selected and user changes to once a month, the entire download/update process starts again. 

3. Timestamp should be saved in internal memory of when last update happened, so when phone restarts it does think it is time to do another download/update if the 30 days of the "once a month" are not yet up. - Will be more helpful on firesticks which start up each time user turns on tv.

4. The list should not be re-downloaded multiple times. Currently, if user starts up app from scratch, each list will download, the update process will happen, then each list completely re-downloads each time again, then the update process, and it keeps repeating more than 4 times. There is no reason for each list to be completely re-downloaded more than four times. 

When I brought this issue up to Feadrak he said "

> the function gets called asynchron based on changes of a variable but has no check for other already running instances." 

So maybe when user downloads blockada, it knows it needs to download list once, then when user turns blokada on it adds another complete download to the que, then when user makes changes to advanced settings it adds another complete download to the que, then user adds a few more list to the block adds another que and so on. I also supect the process currently has blokada download list go through the update process, save the list into download/blokada/paper.io, then re-update the list based on the same list it just stored in download/blokada/paper.io. 

Multiple users have complained about this process. 
![image](https://user-images.githubusercontent.com/38442058/59552568-75953300-8f3d-11e9-8520-1893bc044eea.png)

![image](https://user-images.githubusercontent.com/38442058/59552556-5c8c8200-8f3d-11e9-9bb3-5612dddd7a2c.png)

Granted, the user did have a point, why does blokada initiate the update process if new list haven't been downloaded, as evident by it downloads on wifi only and his phone wasn't on wifi? There is no logical reason for the update process to happen if nothing new has been downloaded because the exact end result will be the same anyway. Same list!

![image](https://user-images.githubusercontent.com/38442058/59552614-2d2a4500-8f3e-11e9-83f0-43a3c969aeb0.png)
I am 100% certain the factors mentioned in this post result in the process being much slower than it could be if these documented bugs were fixed. So it is definitely possible to make the process faster AND SIGNIFICANTLY MORE EFFICIENT

**Comment by kar** [comment]
It will be quite sped up in 4.3

**Comment by rpeter85** [comment]
Just a follow up if you still experience slow start up time with Blokada 4.3.5, @mogarithm
