### ISSUE TITLE
App freezes user in one place 

### ISSUE THREAD

**Issue by PrintableCharacter** [blokadaorg/blokada#412]
I found a small issue in the newest version

How to reproduce:
Step 1: Activate Blokada on the main screen
Step 2: deactivate it
Step 3: swipe up and wait a little until the vpn isn't showing up anymore
Step 4: Swipe down again to leave the VPN 
section

Outcome:
You'll notice that the headline does not change and your app seems frozen until you swipe up again to enter the VPN Section. The headline will match again. After that you can swipe again to see navigate the main screen properly again

A screenrecording and multiple screenshot can be added upon request
The device is a normal mi 8

**Comment by Thomas499** [comment]
Will you verify if this is the same as any of the three issues I listed on the latest post today on https://github.com/blokadaorg/blokada/issues/331#issuecomment-506168916 and can you verify if you found this on a firestick or other device?

**Comment by PrintableCharacter** [comment]
No, it is not the same

**Comment by Thomas499** [comment]
alright. I just notice the freezing too which was documented. Maybe it isn't a particular page but something else that is causing it to freeze. 

Can you test the three issues I documented and verify if they are repeatable? I.e. click activate account and see if the loading screen goes away. List the device you tested on. I tested those with firesticks.

**Comment by PrintableCharacter** [comment]
Would you mind waiting until someone of me voluntarily looks is he/she can reproduce your issues? This is a different case.
Just to avoid unnecessary chatter here. ^^
This isn't meant to be a messaging service

**Comment by Osho-1** [comment]
I want to report a similar issue regarding the app freezing after performing a function.
Device - Mi A1 Stock Android Pie with 4GB RAM
Blokada version - 4.0 (062700)

The issue in my experience occurs when I am trying remove any custom entry under "Blocked Hosts" section of Ad blocking. After removing any entry, the app freezes and pressing any subsequent entry doesn't open drop-down menu to select "remove" option. 
I have to press back button, close the "Blocked Hosts" section, and pull up again by pressing the hamburger button located at the bottom, in order to remove any custom entry.

Attached a video of the issue, please observe the taps on the screen.
https://youtu.be/tttkynsuRl0

**Comment by PrintableCharacter** [comment]
Fixed with 4.1
Excuse the late closing of this.
