### ISSUE TITLE
Hosts from Blocked Hosts list are not consistently blocked

### ISSUE THREAD

**Issue by agnus73** [blokadaorg/blokada#435]
I seem to have the folliwing issue (similar to issue #58): For example I keep adding "graph.facebook.com" to the blocked hosts list but several times per day my device successfully connects to that domain - at least according to blokada's Host-Log. This is also the case for the host "app-measurement.com", other blocked-hosts seem to be blocked more persistently. 
Reading the posts under issue #58 I have to admit I only rarely restart my phone so the issue could be explained by system-caching. But I first installed blokada more than a week ago and the issue was there from the beginning. Restarting doesn't fix it.

What I do:
Look at the host-log, spot entry "graph.facebook.com zugelassen" (accepted in English?), tap on entry, tap on "block"

What happens:
the entry "graph.gacebook.com" appears in the blocked hosts list and is turned on

Expected behaviour:
graph.facebook.com should be blocked henceforth

Actual behaviour:
graph.facebook.com keeps appearing in the host-log as accepted connection

My device: Samsung Galaxy S7
Android 8.0
Blokada 4.1.4

**Comment by agnus73** [comment]
Today, after having added graph.facebook.com umpteen times to the blacklist, the domain send finally to be blocked. So maybe something was fixed in the update to 4.1 and it took some time to take effect?

**Comment by Thomas499** [comment]
Its possible that 4.1 was the fix. But i've experienced this before and the cause was to many host were used. To clarify, the user saw where the app said "x number of host can fit" so the user tried to max out that number. But the user didn't understand that when another app is opened the other app requires memory. If the memory is not available android will free it up from other apps. This means host are deleted, but not all, it only takes what it needs, which is why some will still be blocked when this happens. But blokada doesn't warn you when this happens and it doesn't update the number of host actually blocked if memory is taken from blokada to use on other apps. 

If you are using more than 50% of the max number of host blokada says can fit, you should probably reduce your host list. See if that helps.

Also, lots of whitelist include graph.facebook.com because it is very popular and is required most apps that connect with facebook. Dating apps, games, etc. Not to mention facebook app won't work without it. Take a look at your whitelist and see if any include this.

**Comment by agnus73** [comment]
Thank you for your explanation Thomas499!
I turned off several of my host lists except for four.
But today I discovered, that several of my manually blocked hosts were again accepted by Blokada even though I didn't tamper with my blacklist. graph.facebook.com and app.measurement.com were today contacted by my device even though I added them to my blacklist - again and again.

**Comment by Thomas499** [comment]
Well if you only disabled list that were duplicates (host that were also included in other list) that wouldn't help. For example, if you disable MVPS, AdAway,Dan Pollocks host file, or Peter Lowes host file but still have steven blacks list enabled you are still storing the same number of host as Steven blacks host file is really just those list and one or two others compiled into one list. The same concept with the energizer list. Disable any energizer and hpHost list which are by far the largest list you likely have enabled. In fact you could disable all list and just put graph.facebook.com and app.measurement.com in blacklist that will help debug the issue because then if it still goes through we can rule out the possibility of another app taking memory from blokada and thus removing some of the list (possibly the ones you are noticing. 

Some devices won't let you block certain urls. I.e. you can't block ichnaea.netflix.com on a firestick using blokada. But you can block it on a cell phone using blokada. But if this was the case blokada wouldn't even log it as allowed/blocked. It would be invisible to blokada. 

I highly suspect the links are going through when blokada is downloading/updating list. Blokada is terribly flawed in regards to how often it redownloads list and when this happens it doesn't block anything until the download/upload process is complete (which repeats several times). Documented here https://github.com/blokadaorg/blokada/issues/439 and here https://github.com/blokadaorg/blokada/issues/403 if you have watchdog or fallback enabled disable those. That might help. Especially watchdog. Whoever thought it was a good idea to completely redownload all the list each time the phone connects to a different wifi or looses cell service for a second was not thinking things threw all the all. 

Finally, if you are using V4 or higher, have you bypassed any apps? That would totally explain this behavior. My room mate had to bypass his email on blokada because his email identified the phone was using a vpn and therefor was a security risk. Same with accessing bank accounts. You have to bypass the apps or disable blokada while trying to do those things. But when bypassed, it won't block anything from those apps including graph.facebook.com and app.measurement.com

Hope this helps.

**Comment by agnus73** [comment]
Thanks again for your comprehensive answer, Thomas499.
About bypassing apps: I have only bypassed the following system apps: com.android.carrierconfig, Download-Manager, Google Drive, Google Play Store, com.android.phone, com.android.providers. telephony. All of them were pre-selected after installation, I even excluded a few that were bypassed by default but I assumed bypassing those now on the list woul be necessary for my phone to work correctly - or the would not have been added by default.

I have now disabed ad-blocking altogether and have additionally unselected all host lists - just to be on the safe side. The blacklist is apparently neverheless in effect and it looks like all domains on my blacklist are now blocked cosnistently! Watchdog was disabled and I have also turned off DNS fallback.

**Comment by Thomas499** [comment]
> Should I disable all of them?

No idea. I'd ask on the telegram channel if bypassing the apps makes the host that the bypassed apps use even show up on the logger? If so, then yes. If not, then no. - Unfortunately I was banned from the telegram channel because I tried to explain in the future they should ask for feedback on a clickable mock up before they spend weeks programming something that no one finds comprehensible, intuitive, or user friendly (v4). 

**You disabled ad-blocking (blokada) and now the host in the blacklist are being blocked now that blokada is supposed to be disabled?** This sounds like an epic bug. If this is correct, it is indeed worthy of a new topic. V4 has a lot of bugs so this wouldn't surprise me.

**Comment by agnus73** [comment]
I was a bit astonished too that disabling ad-blocking left the blacklist keep on working. But then again I thought the blacklist is supposed to override everything, right?

**Comment by Thomas499** [comment]
> I was a bit astonished too that disabling ad-blocking left the blacklist keep on working.

I'm pretty sure this isn't the way the app is supposed to work. Disabling blokada is supposed to stop the blacklist from blocking anything and is supposed to turn off the VPN that blokada uses to block stuff. If you have a VPN enabled, you can't access bank accounts and can't access email on some apps because a VPN could be used to do some very bad things.

> I thought the blacklist is supposed to override everything, right?

If blokada is enabled, and the URL isn't whitelist or included in a whitelisted list, or the url isn't coming from an app that is whitelisted or bypassed, yes. That is how it is supposed to work. - Unless the app is downloading or updating list which currently happens a heck of a lot more often than is optimal.

There are some things you can't block using normal blacklist. Such as doubleclick and cws.conviva.com (trackers), ads on IMDb TV app, etc. This is because the URLS add a random string each time. To block them, you would need to enable wildcard functionality. To block ads on IMDb TV app you have to enable "videorolls" as a wildcard. I programmed wildcard functionality to work on V3.8 but the developers didn't transfer it over to V4 nor did they ever make the release public. 

Wildcard functionalty can slow the device down a little though because it works a little differently. On low end devices you don't want to use more than 60 wildcards. On high end devices like the 4k firestick you can use 200+ wildcards without any noticeable slowdown.

**Comment by agnus73** [comment]
https://github.com/blokadaorg/blokada/issues/435#issuecomment-513362061

I did not disable the VPN, only the ad-blocking. I understand it that way, that is only turning off the hosts lists but keeps blacklist functionality working.

**Comment by agnus73** [comment]
https://github.com/blokadaorg/blokada/issues/435#issuecomment-513362061

I did not disable the VPN, only the ad-blocking. I understand it that way, that is only turning off the hosts lists but keeps blacklist functionality working.

Sorry, I am new on GitHub and still don't know how to quote.

**Comment by English106** [comment]
I subscribe to the Blokada VPN and use the New York gateway.

I created a hostfile that mostly targets 1e100.net, googles +20,000 domain name cluster of trackers. 1e100.net shows on android's AppSnitch app as the most frequent connection my phone makes.

For scrutiny:
[ANTdroid.txt](https://github.com/blokadaorg/blokada/files/3505780/ANTdroid.txt)
[Link I use in Blokada](https://raw.githubusercontent.com/English106/ANTdroid/master/hosts)

Many of the connections originate from android system, google play services and play store, and a few other installed apps.

Both AppSnitch and Blokada logfiles regularly report connections to sites in my hostfile. Between my hostfile and the 3 others I have turned on there are about 100,000 entries in total which should be blocked.

Please assist.
