### ISSUE TITLE
I want support for wildcard characters in blocked urls

### ISSUE THREAD

**Issue by notramo** [blokadaorg/blokada#48]
Support for wildcard chars would be cool in urls. E.g. '*.example.com'

**Comment by kar** [comment]
You can just enter "example.com". Do you have any real life examples when you would need it?

**Comment by notramo** [comment]
I added ```archlinux.org``` to the blocking list. I cleared the browser cache, rebooted the phone, and ```archlinux.org``` is blocked, but ```www.archlinux.org``` isn't, and ```bbs.archlinux.org``` is also allowed by Blokada.

**Comment by kar** [comment]
Of course. I must have been tired answering then...

**Comment by Thomas499** [comment]
I second this request. 
**Reason/real life example**
Impossible to block cws.conviva.com without wildcards as documented [https://github.com/StevenBlack/hosts/pull/680](url) 

> Previously, cws.conviva.com tracked non-generic by cws.conviva.com.
This has changed to unique, specific per user via be43a77aab46b0546578grgrtgr3d4ba6506d488.cws.conviva.com (example).

**Comment by animeking9901** [comment]
Google has been doing this with their ad network too

**Comment by Rhodizzle** [comment]
Not sure how to officially throw my support behind this change, but I would place this as higher priority than the UI redesign that happened with v4.

**Comment by Thomas499** [comment]
Careful I was banned from telegram channel for expressing how bad the UI in V4 was and trying to explain they should ask for opinions on a clickable mockup before they spend weeks programming something that everyone hates. 

I do have wildcard functionality working on V3.8 if you want the compiled apk let me know what your username is on telegram and i'll be happy to send it to you. Feedback on it would be great. The admins scrapped the pull request that I made that supports wildcard functionality because they changed the code structure drastically in v4 and didn't post the changes while I was working on the wildcard functionality because they wanted v4 and all the changes to be a secrete. Not very productive.

**Comment by English106** [comment]
Wildcard blocking is definitely needed. It's googles 40,000 strong tracker subdomains used for tracking.

I started curating a list of 1e100.net subdomains which seem to be sequentially generated and made live at will.
