### ISSUE TITLE
Ads not blocket on fotbollskanalen.se

### ISSUE THREAD

**Issue by piddor81** [blokadaorg/blokada#539]
Blokada doesent block ads on fotbollskanalen.se.
Ads fields are greyed out but still there but more importantly ads in videoclips are not removed 

### Steps to reproduce
1.go to fotbollskanalen.se
2.start a video
3.

### Expected behaviour

Video Ads blocked and adfield removed

### Actual behaviour

Video Ads not blocket and är fiels still there

### Configuration
1. Blokada version
4.3.5

2. Device model
Galaxy s8+ SM-G955F

3. Android version / ROM
9

### Questions
1. How long have you been using Blokada? 
3 days

2. How long time ago has the problem started to happen? From start 3 Days ago

3.  How often does this problem happen to you?
Everytime

**Comment by rpeter85** [comment]
Video ads are blocked if they aren't fetched from the same source from where you want to see the video.
After this information:
1.) clear all apps cache to remove already stored ads after you installed Blokada. It is necessary because ads are downloaded and maybe showed from the local storage
2.) ads' remaining field won't be removed by Blokada as this app works on a lower layer, doesn't machinate the application you are using, just blocks the ad (thus, your device doesn't download the app, but the application doesn't show it, the ads are really blocked).

**Comment by piddor81** [comment]
Ok thank you. I tried clearing cache but didnt work. Blokada remove ad fields and video ads on other sites, but i understand difference now thank you

**Comment by piddor81** [comment]
Another question. In the app viafree (swedish) blokada blocks the video ad but the video starts intense flickering after blocket ad

**Comment by rpeter85** [comment]
What could we do with that from Blokada side? :)
