### ISSUE TITLE
Blacklist doesn't always work

### ISSUE THREAD

**Issue by notramo** [blokadaorg/blokada#58]
Adding new domains doesnt work. They will not be blocked.
With a previous version of the app I added custom domains to the blacklist. Blocking of these domains work, but not always.
Steps to reproduce the bug with previously added domains:
- turn off with the switch that appears at the right side of the blacklist item
- reenable that domain
- it won't be blocked

Blokada version: 2.2.2 (installed from F-Droid)
Android 5.1
Optimized blocking

**Comment by kar** [comment]
There is caching involved, so it doesn't always work immediately. Sometimes even until device restart. However it should start working "eventually". Unfortunately there's not much more guarantees on Android. Report back in case it really never starts to work.

**Comment by notramo** [comment]
I cleared the browser cache before testing.

**Comment by kar** [comment]
So I did some more testing and it seems to be working as intended. It's not app caching but system caching. Unfortunately I'm not aware of how to force-clear it. If you are experiencing this problem even after longer waiting, please reopen this issue.

**Comment by agnus73** [comment]
I seem to have the same issue: For example I keep adding "graph.facebook.com" to the blacklist but several times per day my device successfully connects to that domain - at least according to blokada's Host-Log. This is also the case for the host "app-measurement,com", other blacklist-hosts seem to be blocked more persistently. 
Reading the posts above I have to admit I only rarely restart my phone so the issue could be explained by system-caching. But I first installed blokada more than a week ago and the issue was there from the beginning.
