### ISSUE TITLE
Blokada is preventing Signal calls

### ISSUE THREAD

**Issue by jmayday** [blokadaorg/blokada#62]
For some time I was not able to figure out why my Signal calls stopped working. I found this: https://github.com/WhisperSystems/Signal-Android/issues/6990 (my issue was exactly as author described in original post). 
After disabling Blokada my Signal calls started working again.

**Comment by kar** [comment]
Whitelisting doesn't help?

**Comment by jdrissel** [comment]
Witelisting did help for me, however blockada may not be handing this right.  I reported this as a signal bug. Moxie Marlinspike looked at my logs and had this reaction"The Android device never seems to find any ice candidates. Is it on a network that blocks voip?" 

—

**Comment by alexanderadam** [comment]
Happened for me as well. Blokada should block ads and nothing else.
I installed Blokada on my parents phone and we couldn't use Signal calls anymore.
Having to whitelist manually definitely worsen the experience. 😞

**Comment by kar** [comment]
Blokada does support default whitelists already, I'll just add Signal to it. Could you send me the package name of this app? (you can see it in the whitelist)

**Comment by kar** [comment]
Included in the default whitelist. Existing users can use "restore defaults" in the whitelist Quick Actions.

**Comment by HenryGessau** [comment]
I have tried to restore defaults but Signal does not show up in the whitelisted apps.
In the end I uninstalled blokada 😢 and now Signal phone calls work fine.

**Comment by alexanderadam** [comment]
@HenryGessau I had the same problem on the phones of my family members but thought the issue might have been us.

**Comment by kar** [comment]
Have you tried adding signal to the whitelist manually?

**Comment by alexanderadam** [comment]
@kar adding manually worked. It's definitely easy when you _know_ it. :wink: 
It's just strange for people who don't know what the problem might be. Nerds will always be able to find this issue here on GitHub. But not so technical people will just recognize that functionality broke.

Maybe a default option could be something like "Show hits about possible issues" and if blokada blocks something that is not in the whitelist but it is in the  (possibly changed) default whitelist it shows "Hey, something was blocked  in $application that you probably don't want to have blocked".

And maybe an option to apply always the default rules to the custom rules would be nice as well.

PS: Wow, you created _many_ issues in the last hours! I think blokada could really be a game changer. :+1:

**Comment by kar** [comment]
Lack of information how things work is indeed a problem, and we're changing it already. The 3.0.0 has a significantly extended help screen that shows up on first start. It actually explains whitelisting already. More things will come, but all of this takes time to develop. In particular detecting what is mistakenly blocked is not technically as easy as it sounds, and in my opinion not worth the effort until we solve more basic issues.

Keep the feedback coming :)

**Comment by HenryGessau** [comment]
@kar I sure did try to add Signal manually to the whitelist. When I try to add it under **App** it says the app (spelled "Signal") does not exist. I also tried entering 'org.thoughtcrime.securesms' under **Link** and under **App** but that was not accepted either.

**Comment by kar** [comment]
This is probably #102
