### ISSUE TITLE
Whitelist constantly cleared

### ISSUE THREAD

**Issue by Platway** [blokadaorg/blokada#64]
I added some apps to the whitelist. But sometimes they just disappeared. I had to add them back, but they disappeared again in couples of days...

Version 2.2.2-origin-slim.

**Comment by Platway** [comment]
P. S. I have tried uninstalling and then reinstalling the app, and the problem persists.

**Comment by jeroen7s** [comment]
same issue on my device, oneplus 3t with android 7.1

**Comment by Aypac** [comment]
I also experience this issue (on two different devices with two different android versions).
I would like to add my opinion, that this appears to be the most severe bug/issue that is currently open, since there's nobody assigned yet and I simply cannot use important features of one app (Threema Web and Calls) because of it.

**Comment by Tadly** [comment]
I hate doing this but I gotta bump this.
Having to check the Whitelist on a daily basis to ensure those apps didn't get removed again is extremely frustrating especially as e.g google play music starts acting up in the weirdest ways (which is a app I do use for hours on a daily basis).

Anything I can help with to get this resolved anytime soon?

**Comment by alleluia20** [comment]
It is annoying, because I guess that this bug must be easy to fix (please do not say "fix it yourself" :-) , I cannot debug the code :-) , but this kind of bugs are usually caused by a simple and specific mistake...). Furthermore, a new version of Blokada was released after this bug, but the bug was not fixed (which is also annoying).

I hope nobody finds it impolite if I talk of an alternative, just in case someone may find it useful. I am now using DNS66 (if I am correct, Blokada's DNS-blocking is based on DNS66). The problem with DNS66 is that it whitelists almost all system apps, which causes that most in-app ads show. But you can blacklist all the apps at once, and then whitelist the apps you wish. If you find any problems with system upgrades, you can temporarily disable the adblocker.

It was this bug and #81 which made me switch to DNS66. As soon as the two are fixed, I will recommend Blokada again :-)

**Comment by Platway** [comment]
I'm now using DNS66, too. It's much more stable and less buggy.

**Comment by kar** [comment]
I'm working on this, got sidetracked with other things...

**Comment by Tadly** [comment]
It seems like I'm able to reproduce the issue (I was sure I couldn't do that before and it was super sporadic) but here's what I do (maybe it'll help you test it).
 1. Open app
 2. Go to Whitelist -> Add app (e.g. google play music)
 3. Press back twice (so the app closes)
 4. Open androids multitasking few and close the app from there as well
 5. Start app
 6. => Whitelist reset to initial state

If you need me to test a new version, just let me know. I'm happy to help

**Comment by rpeter85** [comment]
@Tadly in my case it didn't reproduce the issue, my list wasn't cleared up.
To be honest, I didn't face this issue since a while, on the 30th of January I reseted my phone and the 7 apps I whitelisted are still there. I had multiple restarts and I even updated the ROM.
I was thinking if it has something to do with the "always on" option, I turned it off. Can you check if it is on or off in your case?

**Comment by Tadly** [comment]
@rpeter85 by "always on" are you referring to the vpn option of android or do you mean the "keep alive" of blokada?

**Comment by rpeter85** [comment]
@Tadly sorry, I mean the "keep alive" option in Blokada.
I use it on my native language and even I set the phone to English, those text didn't change :)

**Comment by Tadly** [comment]
@rpeter85 My whitelist clears with it on and off.
I should add that blokada is turn off right now though.

**Comment by Tadly** [comment]
Uhm, so.. This is resolved now?
I don't see a commit or comment dedicated to this issue which is why I'm asking
  
I'd really like to get back using blokada over dns66 again :)

**Comment by kar** [comment]
Yes, in the next release. I'll push the code soon.
