### ISSUE TITLE
Blokada closes protection for a short while by starting WIFI

### ISSUE THREAD

**Issue by Lavater** [blokadaorg/blokada#646]
1. Connecting to WIFI
2. Blokada protection stops for a short while
3. After a few seconds Blokada restarts

### Expected behaviour
Connecting to WIFI should not shut down protection for a short while.
With data network there's no problem like this.

### Configuration
1. Blokada version: 4.5.2

2. Device model
Samsung S10 (A10)

3. Android version / ROM
Android One UI

### Questions
1. How long have you been using Blokada? 
One month

2. How long time ago has the problem started to happen? 
At least since 4.5.1  

3.  How often does this problem happen to you?
every time

**Comment by Lavater** [comment]
[blokada.log](https://github.com/blokadaorg/blokada/files/4180438/blokada.log)

**Comment by Namnodorel** [comment]
I am experiencing the same problem (on an XZ1C) - not just when switching to WiFi, but in general when switching between mobile data/WiFi, in any direction.
This is problematic because it not only takes a while for Blokada to restart, but any app is completely free to access the internet while it is disabled. And due to. the way Androids job scheduling works, the moment you connect to WiFi is exactly when a lot of apps start sending data.

Note that NetGuard, which functions in a similar way, doesn't have this problem.

**Comment by peterroth** [comment]
@Namnodorel enable "Always on VPN" in system settings - Network & Internet - VPN and you'll be protected against that.

**Comment by Namnodorel** [comment]
> @Namnodorel enable "Always on VPN" in system settings - Network & Internet - VPN and you'll be protected against that.

I already have that enabled, and the only thing it does is showing a notification when Blokada is disabled - but traffic still comes through. I would have to enable blocking non-VPN-connections, but that disables network entirely, even when Blokada is active (iirc it has something to do with DNS requests requiring non-Blokada connections)

**Comment by Lavater** [comment]
Went back to 4.4.4 because in the last 4 days blokada protection stops (didn't not optimize battery consumption for blokada). If I open app, the protecting switch is set. Don't know why I have to open app to start blokada again although Blokada shows active protection inside app but not in taskbar.

**Comment by Lavater** [comment]
There are some people with the same problem in a German forum. All went back to 4.4.4 because of automatic closing protection after some days.

https://www.android-hilfe.de/forum/samsung-galaxy-s10-s10-s10e-s10-5g.3478/blokada-wird-vom-s10-immer-nach-einigen-stunden-einem-tag-deaktiviert.938394-page-3.html#post-11930930

**Comment by ziddey** [comment]
Looks like this old issue is back. Setting a custom dns seems to work

**Comment by Namnodorel** [comment]
> Setting a custom dns seems to work

Can't confirm - I switched to AdGuard, and the problem persisted.

**Comment by donateur** [comment]
I'm seeing this on a Pixel 3, running Android 10 (March update) with Blockada 4.5.2

What is worse, it creates a painful situation when I sign in to my employer's WiFi through a captive portal.  Here's a series of events:

1. Using 4G connection, Blockada "VPN" enabled
2. Work WiFi access point detected.
3. Android connects to the access point.
4. Blockada drops out
5. I click the "you must sign in to this network" message in the Android blind
6. Blockada reconnects
7. A page which would show the captive portal loads - but it fails due to Blockada having just loaded it is interrupted and fails.  I'm unable to sign in to the captive portal and have no internet connection at all.

I've found the most reliable thing is to disable Blockada at step 4, then sign in to the captive portal.  After signing in to an captive portal Android automatically switches you back to the last app you had open, which is Blockada, so I click reconnect.  It's a pain!

**Comment by Testertime** [comment]
> @Namnodorel enable "Always on VPN" in system settings - Network & Internet - VPN and you'll be protected against that.

I tried this on my Android 8.1 phone, but sadly this doesn't fix the constant reconnections. It appears to be something with the (re)connection logic in Blokada, since I haven't had this behavior with other apps.

**Comment by c933103** [comment]
Similar thing happened to me.
Step to reproduve:
1. Set an invalid DNS server in blokada (so that no app could be able to resolve their url and reach their server)
2. Wait a while so that your apps are supposed to be receiving puah notifications yet are unable to because of the invalid DNS setting (or just send an email to yourself from computer or generate push notification to your apps using other methods)
3. Switch from Wi-Fi to cellular OR from cellular to Wi-Fi (the bug seems to happens both ways. If it didn't produce the result below ghen switch a few times more)
4. What happened: All the unreceived push notification flushed in righ after the change of network connection type
