### ISSUE TITLE
I want support for apps that use Google play ad service to fix games like golf rival

### ISSUE THREAD

**Issue by cocokola** [blokadaorg/blokada#760]
### Actual behavior 
Apps that utilize google play ad service are currently an all or nothing proposition.  Perhaps folks could add to a list of apps affected by this problem. Ultimately, instead of the app pulling the ads, it is proxied by Google ad services.   So this leaves the user to either
1)disable blokada to allow the ad to display thereby gaining some reward,then enable blokada when done
2) add the Google play ad service to whitelisted, which defeats the purpose of having blokada 

### Expected behaviour
Ability to flag aps as dependent on another app, ability to select the app or provide list of common apos such as GPS. Whenever the app is used, temporary whitelist the dependant app listed.  When the app closes  re-enable whitelist.   Note, need to verify if dependent app is already whitelisted, then do nothing or put stare back to initial state

### Steps to reproduce  
Install golf rival.   On main screen, bottom left is 'free rewards'  click on this, then click on the rewards that require an ad displayed.  Follow the examples above.  If you whitelist the Google play service, then this works as it should when the main app is whitelisted. 

### Configuration
1. Blokada version:4.7.3
2. Device model: note 10 ultra
3. Android version 10

There are some apps that refuse to run at all because of this depenacy.  It would be a way to differentiate this app from similar products.

**Comment by peterroth** [comment]
Hey,
Isn't bypassing the given app enough in such a case?

**Comment by cocokola** [comment]
You don't understand.   Think three tier model.   The app is tier 1.  Whitelisting it does nothing.  Tier 2. Is the ad service.  This is what you could whitelist, but then every app, service that use this is whitelisted.  This includes Chrome, Google play, golf rival, and thousands of others  tier 3. Is the ad back end   yes you can whitelist v these addresses, but same result at whitelisting tier2 or worse.

Saying this is same as whitelisting app is missing the point.
 In order to make this work, tier 2 has to be blocked depending on what tier 1app is used.  In practice if implemented, yes you would whitelist the game /app but you would need to check a box indicating it uses the tier 2app, which at first could be just Google ad services as it may be the only one, so a checkbox would suffice.

**Comment by peterroth** [comment]
You can bypass hostnames as well, not only applications.

**Comment by cocokola** [comment]
yes, and how would this change the behavior or be applicable to my example?   If I bypass hostnames, then that host is the generic host for google play services, ergo, all apps get ads again.. Strike TWO!

my request holds water, take a moment to drink it!

**Comment by peterroth** [comment]
Blokada doesn't distinguish what is blocks. It blocks what is on the list. It is being said, you can either bypass:
1. app's traffic
2. hostname

You can't narrow it further down to "in given app, given hostnames are free to be accessed, rest aren't" because
1. Blokada won't check if there are new hosts that you need to bypass/access
2. Blokada doesn't track (yet) which apps are accessing which hostnames, and from those, which ones are blocked and which ones aren't.

**Comment by cocokola** [comment]
Hence this is a feature request.  It would be fairly trivial to research how to do this beside the suggestions I provided.

Are you saying too bad not going to even look at it?

**Comment by ps100000** [comment]
I did some research by having a look at the decompiled smali files of the app and as I expected the communication between the app and google play service seems to not be based on sending network requests but rather the app interacting with a service implemented by the com.google.android.gms package. If that's truly the case all requests to load ads are managed by google play services and there is nothing we could use to allow ads for specific apps (except for maybe HTTPS filtering which we don't want to do). Intersecting the communication between app and service afaik isn't possible so for know this issue seems unsolvable,

**Comment by peterroth** [comment]
I also had a few hours research a week ago, the problem here is that the ads the apps (except some of them) are showing based on your Google [Advertising ID](https://support.google.com/googleplay/android-developer/answer/6048248?hl=en), means it goes through Google and use Google Play to provide you the content.
From this point, I would just repeat what @ps100000 wrote above. It's very challenging and without encrypted communication filtering about impossible.
