### ISSUE TITLE
[Feature Request] Ability to see which app is making the call on Activity Detail screen

### ISSUE THREAD

**Issue by sidhuharry** [blokadaorg/blokada#843]
It would be a great improvement if we could see which app is the source of some network calls. We can remove the repeatedly offending apps.

**Comment by peterroth** [comment]
The problem here is that with newer and newer Android versions the app isolation doesn't allow one app to check what the other app does or tries to access.
With Android 11, apps can't even list what is installed on the device (it is used for bypassing filtering in Blokada).
So without the device being rooted this is impossible.

**Comment by e-t-l** [comment]
> With Android 11, apps can't even list what is installed on the device (it is used for bypassing filtering in Blokada).

What exactly does this mean? Does Bypass filtering require that Blokada can differentiate requests from different apps?

**Comment by peterroth** [comment]
Something similar. Blokada will exclude the bypassed apps from the VPN tunnel (hence the name: bypassed), but on Android 11 it can't even check what apps you have installed on your phone, what means you can't bypass apps if Blokada is built against API level 30.

**Comment by androidacy** [comment]
Adguard manages to do this, being built against sdk29.

SDK requirements aren't even really a concern until android flat out blocks that version: you can't have the full version in the play store anyway because it's an AdBlocker.
