### ISSUE TITLE
Android: VPN connection is occasionally lost (Blokada libre)

### ISSUE THREAD

**Issue by WebworkrNet** [blokadaorg/blokada#905]
1. **What exactly is not working?** 
Android occasionally reports that the VPN connection has been lost and offers to open Blokada.
If one then opens Blokada, however, it is displayed that Blokada is active (again?).
2. **How to reproduce your problem (steps you have taken that caused the problem)**  Blokada is activated and runs in the background.
3. **Which app version and which platform are you using?**
Samsung Galaxy XCover 4s (SM-G398FN)
Android 11
Blokada 5.18.0 (via F-Droid)
Libre
4. **DNS server issues are a common cause for some problems, have you tried selecting another DNS?**
No
5. **Have you tried disabling DNS over HTTPS, or toggle other settings in Blokada?**
No

**Comment by WebworkrNet** [comment]
There may be a connection between tickets #904 and 905.

**Comment by WebworkrNet** [comment]
![Screenshot_20211110-153824_One UI Home](https://user-images.githubusercontent.com/43509007/141135278-ade70b63-b0a3-4fe7-9f0b-238bc29636f4.jpg)
![Screenshot_20211110-153944](https://user-images.githubusercontent.com/43509007/141135288-beae1771-4150-4558-b3bf-c7faf71ac694.jpg)

**Comment by TomasRiker** [comment]
Same issue here on Android 12 (Google Pixel 4a (5G)).

Important additional information: After restarting Blokada, **it doesn't notice which network is the current one**. Meaning only "_All networks_" is green, but not "_All Wi-Fi networks_" or "_All mobile networks_", and any settings configured there are ignored. In my case, it would then ignore the "_Prefer network DNS_" setting, and I would not be able to reach anything in my local network. The issue is fixed after disabling and enabling Wi-Fi.

**Comment by angrox** [comment]
I face the same issue as @TomasRiker: Blokada does not find the correct network to apply different DNS services after the mobile goes into sleep. (Android 12, also Pixel 4a 5g)
It would be nice if we could disable the dns routing completly.

**Comment by TomasRiker** [comment]
I went back to Blokada 4, which allows disabling the DNS stuff altogether. Working much better than Blokada 5.

**Comment by kar** [comment]
There is another issue open for the network detection case, thanks!
